using System.Collections.Generic;

namespace E_commerce.Models
{
    public static class StaticData
    {
        public static List<Governorate> yemenGovernorates = new List<Governorate>
{
    new Governorate(1, "عدن"),
    new Governorate(2, "عمران"),
    new Governorate(3, "الامانة"),
    new Governorate(4, "صنعاء"),
    new Governorate(5, "الحديدة"),
    new Governorate(6, "تعز"),
    new Governorate(7, "حجة"),
    new Governorate(8, "حضرموت"),
    new Governorate(9, "إب"),
    new Governorate(10, "ذمار"),
    new Governorate(11, "لحج"),
    new Governorate(12, "الجوف"),
    new Governorate(13, "المحويت"),
    new Governorate(14, "ريمة"),
    new Governorate(15, "الضالع"),
    new Governorate(16, "شبوة"),
    new Governorate(17, "أبين"),
    new Governorate(18, "المهرة"),
    new Governorate(19, "البيضاء"),
    new Governorate(20, "صعدة"),
    new Governorate(21, "مارب"),
    new Governorate(22, "سقطرى")
};
        public static List<Directorate> allDirectorates = new List<Directorate>
{
     new Directorate { Name = "المنصورة", GovernorateId = 1 },
    new Directorate { Name = "المعلا", GovernorateId = 1 },
    new Directorate { Name = "كريتر", GovernorateId = 1 },
    new Directorate { Name = "الشيخ عثمان", GovernorateId = 1 },
    new Directorate { Name = "دار سعد", GovernorateId = 1 },
    new Directorate { Name = "خور مكسر", GovernorateId = 1 },
    new Directorate { Name = "التواهي", GovernorateId = 1 },
    new Directorate { Name = "البريقة", GovernorateId = 1 },


    new Directorate { Name = "صعده", GovernorateId = 20 },
    new Directorate { Name = "منبه", GovernorateId = 20 },
    new Directorate { Name = "مجز", GovernorateId = 20 },
    new Directorate { Name = "كتاف", GovernorateId = 20 },
    new Directorate { Name = "قطابر", GovernorateId = 20 },
    new Directorate { Name = "غمر", GovernorateId = 20 },
    new Directorate { Name = "الظاهر", GovernorateId = 20 },
    new Directorate { Name = "الصفراء", GovernorateId = 20 },
    new Directorate { Name = "شداء", GovernorateId = 20 },
    new Directorate { Name = "سحار", GovernorateId = 20 },
    new Directorate { Name = "ساقين", GovernorateId = 20 },
    new Directorate { Name = "رازح", GovernorateId = 20 },
    new Directorate { Name = "حيدان", GovernorateId = 20 },
    new Directorate { Name = "الحشوة", GovernorateId = 20 },
    new Directorate { Name = "باقم", GovernorateId = 20 },
    new Directorate { Name = "ال سالم", GovernorateId = 20 },

    new Directorate { Name = "يريم", GovernorateId = 9 },
    new Directorate { Name = "النادرة", GovernorateId = 9 },
    new Directorate { Name = "مذيخرة", GovernorateId = 9 },
    new Directorate { Name = "المخادر", GovernorateId = 9 },
    new Directorate { Name = "القفر", GovernorateId = 9 },
    new Directorate { Name = "الفرع", GovernorateId = 9 },
    new Directorate { Name = "العدين", GovernorateId = 9 },
    new Directorate { Name = "الشعر", GovernorateId = 9 },
    new Directorate { Name = "السياني", GovernorateId = 9 },
    new Directorate { Name = "السدة", GovernorateId = 9 },
    new Directorate { Name = "السبرة", GovernorateId = 9 },
    new Directorate { Name = "الرضمة", GovernorateId = 9 },
    new Directorate { Name = "ذي السفال", GovernorateId = 9 },
    new Directorate { Name = "الحزم", GovernorateId = 9 },
    new Directorate { Name = "حبيش", GovernorateId = 9 },
    new Directorate { Name = "جبلة", GovernorateId = 9 },
    new Directorate { Name = "بعدان", GovernorateId = 9 },
    new Directorate { Name = "ريف اب", GovernorateId = 9 },
    new Directorate { Name = "الظهار", GovernorateId = 9 },
    new Directorate { Name = "المشنة", GovernorateId = 9 },


     new Directorate { Name = "بني الحارث", GovernorateId = 3 },
    new Directorate { Name = "شعوب", GovernorateId = 3 },
    new Directorate { Name = "الثورة", GovernorateId = 3 },
    new Directorate { Name = "معين", GovernorateId = 3 },
    new Directorate { Name = "التحرير", GovernorateId = 3 },
    new Directorate { Name = "الوحدة", GovernorateId = 3 },
    new Directorate { Name = "السبعين", GovernorateId = 3 },
    new Directorate { Name = "الصافية", GovernorateId = 3 },
    new Directorate { Name = "أزال", GovernorateId = 3 },
    new Directorate { Name = "صنعاء القديمة", GovernorateId = 3 },

        new Directorate { Name = "عيال يزيد", GovernorateId = 2 },
    new Directorate { Name = "ثلاء", GovernorateId = 2 },
    new Directorate { Name = "بني صريم", GovernorateId = 2 },
    new Directorate { Name = "عمران", GovernorateId = 2 },
    new Directorate { Name = "مسور", GovernorateId = 2 },
    new Directorate { Name = "المدان", GovernorateId = 2 },
    new Directorate { Name = "القفله", GovernorateId = 2 },
    new Directorate { Name = "عيال سريح", GovernorateId = 2 },
    new Directorate { Name = "العشه", GovernorateId = 2 },
    new Directorate { Name = "حبور", GovernorateId = 2 },
    new Directorate { Name = "صوير", GovernorateId = 2 },
    new Directorate { Name = "شهاره", GovernorateId = 2 },
    new Directorate { Name = "السوده", GovernorateId = 2 },
    new Directorate { Name = "السود", GovernorateId = 2 },
    new Directorate { Name = "ريده", GovernorateId = 2 },
    new Directorate { Name = "ذيبين", GovernorateId = 2 },
    new Directorate { Name = "خمر", GovernorateId = 2 },
    new Directorate { Name = "خارف", GovernorateId = 2 },
    new Directorate { Name = "حوث", GovernorateId = 2 },
    new Directorate { Name = "حرف سفيان", GovernorateId = 2 },

     new Directorate { Name = "الوضيع", GovernorateId = 17 },
    new Directorate { Name = "مودية", GovernorateId = 17 },
    new Directorate { Name = "المحفد", GovernorateId = 17 },
    new Directorate { Name = "لودر", GovernorateId = 17 },
    new Directorate { Name = "سرار", GovernorateId = 17 },
    new Directorate { Name = "سباح", GovernorateId = 17 },
    new Directorate { Name = "رصد", GovernorateId = 17 },
    new Directorate { Name = "خنفر", GovernorateId = 17 },
    new Directorate { Name = "جيشان", GovernorateId = 17 },
    new Directorate { Name = "أحور", GovernorateId = 17 },
    new Directorate { Name = "زنجبار", GovernorateId = 17 },

    new Directorate { Name = "ولد ربيع", GovernorateId = 19 },
    new Directorate { Name = "نعمان", GovernorateId = 19 },
    new Directorate { Name = "ناطع", GovernorateId = 19 },
    new Directorate { Name = "الملاجم", GovernorateId = 19 },
    new Directorate { Name = "مكيراس", GovernorateId = 19 },
    new Directorate { Name = "مسورة", GovernorateId = 19 },
    new Directorate { Name = "القريشية", GovernorateId = 19 },
    new Directorate { Name = "العرش", GovernorateId = 19 },
    new Directorate { Name = "الطفة", GovernorateId = 19 },
    new Directorate { Name = "الصومعة", GovernorateId = 19 },
    new Directorate { Name = "صباح", GovernorateId = 19 },
    new Directorate { Name = "الشرية", GovernorateId = 19 },
    new Directorate { Name = "السوادية", GovernorateId = 19 },
    new Directorate { Name = "الرياشية", GovernorateId = 19 },
    new Directorate { Name = "ردمان", GovernorateId = 19 },
    new Directorate { Name = "رداع", GovernorateId = 19 },
    new Directorate { Name = "ذي ناعم", GovernorateId = 19 },
    new Directorate { Name = "آل حميقان", GovernorateId = 19 },
    new Directorate { Name = "البيضاء", GovernorateId = 19 },
    new Directorate { Name = "المدينة", GovernorateId = 19 },

    new Directorate { Name = "الوازعيه", GovernorateId = 6 },
    new Directorate { Name = "موزع", GovernorateId = 6 },
    new Directorate { Name = "المواسط", GovernorateId = 6 },
    new Directorate { Name = "مقبنه", GovernorateId = 6 },
    new Directorate { Name = "المعافر", GovernorateId = 6 },
    new Directorate { Name = "مشرعه وحدنان", GovernorateId = 6 },
    new Directorate { Name = "المسراخ", GovernorateId = 6 },
    new Directorate { Name = "المخاء", GovernorateId = 6 },
    new Directorate { Name = "ماويه", GovernorateId = 6 },
    new Directorate { Name = "الصلو", GovernorateId = 6 },
    new Directorate { Name = "صبر الموادم", GovernorateId = 6 },
    new Directorate { Name = "الشمايتين", GovernorateId = 6 },
    new Directorate { Name = "شرعب السلام", GovernorateId = 6 },
    new Directorate { Name = "شرعب الرونه", GovernorateId = 6 },
    new Directorate { Name = "سامع", GovernorateId = 6 },
    new Directorate { Name = "ذباب", GovernorateId = 6 },
    new Directorate { Name = "خدير", GovernorateId = 6 },
    new Directorate { Name = "حيفان", GovernorateId = 6 },
    new Directorate { Name = "جبل حبشي", GovernorateId = 6 },
    new Directorate { Name = "التعزيه", GovernorateId = 6 },
    new Directorate { Name = "صاله", GovernorateId = 6 },
    new Directorate { Name = "القاهره", GovernorateId = 6 },
    new Directorate { Name = "المظفر", GovernorateId = 6 },

     new Directorate { Name = "المراشي", GovernorateId = 12 },
    new Directorate { Name = "العنان", GovernorateId = 12 },
    new Directorate { Name = "المطمة", GovernorateId = 12 },
    new Directorate { Name = "المصلوب", GovernorateId = 12 },
    new Directorate { Name = "المتون", GovernorateId = 12 },
    new Directorate { Name = "الغيل", GovernorateId = 12 },
    new Directorate { Name = "الزاهر", GovernorateId = 12 },
    new Directorate { Name = "رحوزة", GovernorateId = 12 },
    new Directorate { Name = "الخلق", GovernorateId = 12 },
    new Directorate { Name = "الشعف", GovernorateId = 12 },
    new Directorate { Name = "الحميدات", GovernorateId = 12 },
    new Directorate { Name = "الحزم", GovernorateId = 12 },

    new Directorate { Name = "حرض", GovernorateId = 7 },
    new Directorate { Name = "الجميمة", GovernorateId = 7 },
    new Directorate { Name = "بني قيس", GovernorateId = 7 },
    new Directorate { Name = "بني العوام", GovernorateId = 7 },
    new Directorate { Name = "بكيل المير", GovernorateId = 7 },
    new Directorate { Name = "افلح اليمن", GovernorateId = 7 },
    new Directorate { Name = "افلح الشام", GovernorateId = 7 },
    new Directorate { Name = "اسلم", GovernorateId = 7 },
    new Directorate { Name = "مديرية حجة", GovernorateId = 7 },
    new Directorate { Name = "المدينة", GovernorateId = 7 },
    new Directorate { Name = "وضرة", GovernorateId = 7 },
    new Directorate { Name = "وشحة", GovernorateId = 7 },
    new Directorate { Name = "نجرة", GovernorateId = 7 },
    new Directorate { Name = "ميدي", GovernorateId = 7 },
    new Directorate { Name = "المفتاح", GovernorateId = 7 },
    new Directorate { Name = "المغربة", GovernorateId = 7 },
    new Directorate { Name = "مستباء", GovernorateId = 7 },
    new Directorate { Name = "المحابشة", GovernorateId = 7 },
    new Directorate { Name = "مبين", GovernorateId = 7 },
    new Directorate { Name = "كعيدنة", GovernorateId = 7 },
    new Directorate { Name = "كشر", GovernorateId = 7 },
    new Directorate { Name = "كحلان عفار", GovernorateId = 7 },
    new Directorate { Name = "كحلان الشرف", GovernorateId = 7 },
    new Directorate { Name = "قفل شمر", GovernorateId = 7 },
    new Directorate { Name = "قارة", GovernorateId = 7 },
    new Directorate { Name = "عبس", GovernorateId = 7 },
    new Directorate { Name = "الشغادرة", GovernorateId = 7 },
    new Directorate { Name = "شرس", GovernorateId = 7 },
    new Directorate { Name = "الشاهل", GovernorateId = 7 },
    new Directorate { Name = "خيران", GovernorateId = 7 },
    new Directorate { Name = "حيران", GovernorateId = 7 },

    new Directorate { Name = "الزيدية", GovernorateId = 5 },
    new Directorate { Name = "الزهرة", GovernorateId = 5 },
    new Directorate { Name = "زبيد", GovernorateId = 5 },
    new Directorate { Name = "الدريهمي", GovernorateId = 5 },
    new Directorate { Name = "الخوخه", GovernorateId = 5 },
    new Directorate { Name = "حيس", GovernorateId = 5 },
    new Directorate { Name = "الحجيلة", GovernorateId = 5 },
    new Directorate { Name = "الجراحي", GovernorateId = 5 },
    new Directorate { Name = "جبل رأس", GovernorateId = 5 },
    new Directorate { Name = "التحيتا", GovernorateId = 5 },
    new Directorate { Name = "بيت الفقيه", GovernorateId = 5 },
    new Directorate { Name = "برع", GovernorateId = 5 },
    new Directorate { Name = "باجل", GovernorateId = 5 },
    new Directorate { Name = "الحالي", GovernorateId = 5 },
    new Directorate { Name = "الميناء", GovernorateId = 5 },
    new Directorate { Name = "الحوك", GovernorateId = 5 },
    new Directorate { Name = "المنيرة", GovernorateId = 5 },
    new Directorate { Name = "المنصورية", GovernorateId = 5 },
    new Directorate { Name = "المغلاف", GovernorateId = 5 },
    new Directorate { Name = "المراوعة", GovernorateId = 5 },
    new Directorate { Name = "اللحية", GovernorateId = 5 },
    new Directorate { Name = "كمران", GovernorateId = 5 },
    new Directorate { Name = "القناوص", GovernorateId = 5 },
    new Directorate { Name = "الضحي", GovernorateId = 5 },
    new Directorate { Name = "الصليف", GovernorateId = 5 },
    new Directorate { Name = "السخنة", GovernorateId = 5 },

    new Directorate { Name = "القطن", GovernorateId = 8 },
    new Directorate { Name = "سيؤون", GovernorateId = 8 },
    new Directorate { Name = "يبعث", GovernorateId = 8 },
    new Directorate { Name = "قلنسية وعبدالكوري", GovernorateId = 8 },
    new Directorate { Name = "غيل بن يمين", GovernorateId = 8 },
    new Directorate { Name = "غيل باوزير", GovernorateId = 8 },
    new Directorate { Name = "الضليعة", GovernorateId = 8 },
    new Directorate { Name = "الشحر", GovernorateId = 8 },
    new Directorate { Name = "الريدة وقصيعر", GovernorateId = 8 },
    new Directorate { Name = "الديس الشرقية", GovernorateId = 8 },
    new Directorate { Name = "دوعن", GovernorateId = 8 },
    new Directorate { Name = "حجر", GovernorateId = 8 },
    new Directorate { Name = "بروم وميفع", GovernorateId = 8 },
    new Directorate { Name = "ارياف المكلا", GovernorateId = 8 },
    new Directorate { Name = "مدينة المكلا", GovernorateId = 8 },


    new Directorate { Name = "بيحان", GovernorateId = 10 },
    new Directorate { Name = "وصاب العالي", GovernorateId = 10 },
    new Directorate { Name = "وصاب السافل", GovernorateId = 10 },
    new Directorate { Name = "ميفعة عنس", GovernorateId = 10 },
    new Directorate { Name = "المنار", GovernorateId = 10 },
    new Directorate { Name = "مغرب عنس", GovernorateId = 10 },
    new Directorate { Name = "عنس", GovernorateId = 10 },
    new Directorate { Name = "عتمة", GovernorateId = 10 },
    new Directorate { Name = "ضوران آنس", GovernorateId = 10 },
    new Directorate { Name = "الحداء", GovernorateId = 10 },
    new Directorate { Name = "جهران", GovernorateId = 10 },
    new Directorate { Name = "جبل الشرق", GovernorateId = 10 },
    new Directorate { Name = "المدينة", GovernorateId = 10 },


     new Directorate { Name = "نصاب", GovernorateId = 16 },
    new Directorate { Name = "ميفعة", GovernorateId = 16 },
    new Directorate { Name = "مرخة العليا", GovernorateId = 16 },
    new Directorate { Name = "مرخة السفلى", GovernorateId = 16 },
    new Directorate { Name = "عين", GovernorateId = 16 },
    new Directorate { Name = "عسيلان", GovernorateId = 16 },
    new Directorate { Name = "عرماء", GovernorateId = 16 },
    new Directorate { Name = "الطلح", GovernorateId = 16 },
    new Directorate { Name = "الصعيد", GovernorateId = 16 },
    new Directorate { Name = "الروضة", GovernorateId = 16 },
    new Directorate { Name = "رضوم", GovernorateId = 16 },
    new Directorate { Name = "دهر", GovernorateId = 16 },
    new Directorate { Name = "حطيب", GovernorateId = 16 },
    new Directorate { Name = "حبان", GovernorateId = 16 },
    new Directorate { Name = "جردان", GovernorateId = 16 },
    new Directorate { Name = "عتق", GovernorateId = 16 },




        new Directorate { Name = "صنعاء الجديدة", GovernorateId = 4 },
    new Directorate { Name = "همدان", GovernorateId = 4 },
    new Directorate { Name = "نهم", GovernorateId = 4 },
    new Directorate { Name = "مناخه", GovernorateId = 4 },
    new Directorate { Name = "الطيال", GovernorateId = 4 },
    new Directorate { Name = "صعفان", GovernorateId = 4 },
    new Directorate { Name = "سنحان وبني بهلول", GovernorateId = 4 },
    new Directorate { Name = "خولان", GovernorateId = 4 },
    new Directorate { Name = "الحيمة الداخلية", GovernorateId = 4 },
    new Directorate { Name = "الحيمة الخارجية", GovernorateId = 4 },
    new Directorate { Name = "الحصن", GovernorateId = 4 },
    new Directorate { Name = "جحانه", GovernorateId = 4 },
    new Directorate { Name = "بني مطر", GovernorateId = 4 },
    new Directorate { Name = "بني ظبيان", GovernorateId = 4 },
    new Directorate { Name = "بني حشيش", GovernorateId = 4 },
    new Directorate { Name = "بلاد الروس", GovernorateId = 4 },
    new Directorate { Name = "ارحب", GovernorateId = 4 },

     new Directorate { Name = "قعطبة", GovernorateId = 15 },
    new Directorate { Name = "الشعيب", GovernorateId = 15 },
    new Directorate { Name = "دمت", GovernorateId = 15 },
    new Directorate { Name = "الحصين", GovernorateId = 15 },
    new Directorate { Name = "الحشاء", GovernorateId = 15 },
    new Directorate { Name = "جحاف", GovernorateId = 15 },
    new Directorate { Name = "جبن", GovernorateId = 15 },
    new Directorate { Name = "الازارق", GovernorateId = 15 },
    new Directorate { Name = "الضالع", GovernorateId = 15 },


     new Directorate { Name = "يافع", GovernorateId = 11 },
    new Directorate { Name = "مديرية يهر", GovernorateId = 11 },
    new Directorate { Name = "مديرية الملاح", GovernorateId = 11 },
    new Directorate { Name = "مديرية المقاطره", GovernorateId = 11 },
    new Directorate { Name = "مديرية المفلحي", GovernorateId = 11 },
    new Directorate { Name = "مديرية المضاربه", GovernorateId = 11 },
    new Directorate { Name = "مديرية المسيمير", GovernorateId = 11 },
    new Directorate { Name = "مديرية لبعوس", GovernorateId = 11 },
    new Directorate { Name = "مديرية القبيطة", GovernorateId = 11 },
    new Directorate { Name = "مديرية طور الباحه", GovernorateId = 11 },
    new Directorate { Name = "مديرية الحبيلين", GovernorateId = 11 },
    new Directorate { Name = "مديرية حبيل جبر", GovernorateId = 11 },
    new Directorate { Name = "مديرية حالمين", GovernorateId = 11 },
    new Directorate { Name = "مديرية تبن", GovernorateId = 11 },
    new Directorate { Name = "مديرية الحد", GovernorateId = 11 },
    new Directorate { Name = "الحوطة", GovernorateId = 11 },


     new Directorate { Name = "المدينه", GovernorateId = 21 },
    new Directorate { Name = "رحبة", GovernorateId = 21 },
    new Directorate { Name = "حريب القراميش", GovernorateId = 21 },
    new Directorate { Name = "حريب", GovernorateId = 21 },
    new Directorate { Name = "الجوبة", GovernorateId = 21 },
    new Directorate { Name = "جبل مراد", GovernorateId = 21 },
    new Directorate { Name = "بدبدة", GovernorateId = 21 },
    new Directorate { Name = "مأرب الوادي", GovernorateId = 21 },
    new Directorate { Name = "مدغل", GovernorateId = 21 },
    new Directorate { Name = "مجزر", GovernorateId = 21 },
    new Directorate { Name = "ماهلية", GovernorateId = 21 },
    new Directorate { Name = "العابدية", GovernorateId = 21 },
    new Directorate { Name = "صرواح", GovernorateId = 21 },
    new Directorate { Name = "رغوان", GovernorateId = 21 },

     new Directorate { Name = "ملحان", GovernorateId = 13 },
    new Directorate { Name = "الطويله", GovernorateId = 13 },
    new Directorate { Name = "شبام", GovernorateId = 13 },
    new Directorate { Name = "الرجم", GovernorateId = 13 },
    new Directorate { Name = "الخبت", GovernorateId = 13 },
    new Directorate { Name = "حفاش", GovernorateId = 13 },
    new Directorate { Name = "بني سعد", GovernorateId = 13 },
    new Directorate { Name = "المحويت", GovernorateId = 13 },
    new Directorate { Name = "مدينة المحويت", GovernorateId = 13 },

     new Directorate { Name = "منعر", GovernorateId = 18 },
    new Directorate { Name = "المسيلة", GovernorateId = 18 },
    new Directorate { Name = "قشن", GovernorateId = 18 },
    new Directorate { Name = "شحن", GovernorateId = 18 },
    new Directorate { Name = "سيحوت", GovernorateId = 18 },
    new Directorate { Name = "حوف", GovernorateId = 18 },
    new Directorate { Name = "حصوين", GovernorateId = 18 },
    new Directorate { Name = "حات", GovernorateId = 18 },
    new Directorate { Name = "الغيضة", GovernorateId = 18 },


     new Directorate { Name = "مزهر", GovernorateId = 14 },
    new Directorate { Name = "كسمه", GovernorateId = 14 },
    new Directorate { Name = "السلفيه", GovernorateId = 14 },
    new Directorate { Name = "الجعفريه", GovernorateId = 14 },
    new Directorate { Name = "بلاد الطعام", GovernorateId = 14 },
    new Directorate { Name = "الجبين", GovernorateId = 14 },


    new Directorate { Name = "حديبو", GovernorateId = 22 }



    };






        public static List<Roles> Roles = new List<Roles> { new Roles { Name = "مشرف عام" }, new Roles { Name = "جمعية" }, new Roles { Name = "مستفيد" } };

    }
    public class Roles
    {
        public string Name { get; set; }
    }
}
